Portfolio: setup and mobile first.
samif1/PORTFOLIO pull request #2
Opened 2022-10-28 23:32 UTC by samif1

Use Flexbox to place elements in the page.
Use CSS Grid to place elements in the page.
Build a personal portfolio site.

2022-10-28 23:52 UTC, Gopxfs commented
# STATUS: INVALID REQUEST

Hi @samif1 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that doesn't contain a professional Pull Request. Check [this link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to understand more about it. Please notice that your PR title is different than the exercise you requested a review.

Your Code Review Request will be marked invalid in your Dashboard, so please submit a new one once ready 🙏.
Invalid requests don't count as a review, so don't worry about that 😄!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-29 00:35 UTC, tufoinnkuo10 requested changes
## Hi @samif1 

There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

## Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-29 00:35 UTC, tufoinnkuo10 commented on index.html
> +          />
- [ ] kindly use the correct background color like the figma version .. `#F7F7F9;`

yours
![Screenshot (568)_LI](https://user-images.githubusercontent.com/65298048/198753390-427850e6-c0ca-4b89-bd11-f97051a34146.jpg)
figma
![Screenshot (567)_LI](https://user-images.githubusercontent.com/65298048/198753415-185a07e7-e317-4ac7-9f07-25004748266c.jpg)

2022-10-29 00:35 UTC, tufoinnkuo10 commented on index.html
> +        <p class="supportive-text">Let's Connect</p>
- [ ] kindly use the correct color on the` lets connect `heading so it follows the figma design
- [ ] lets connect is a heading so it should be in an `hx tag`
- [ ] you seem to be missing the social icons. please implement that

yours
![Screenshot (570)_LI](https://user-images.githubusercontent.com/65298048/198753545-7776b026-62ad-443a-9452-cf7d3163c18e.jpg)
figma
![Screenshot (569)_LI](https://user-images.githubusercontent.com/65298048/198753574-b321e23c-24d6-4acf-b632-41ba7b00f01b.jpg)

2022-10-29 08:07 UTC, Favourezeugwa approved these changes
## STATUS: APPROVED 🏆 🥇 🍹 

Hi @samif1 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉  🎉 🎉

![approvedstamp](https://user-images.githubusercontent.com/99246359/198821025-c3b4736d-963b-4590-ab74-6ca7f313fff4.gif)

## Highlights 💯 
- No Linter errors ✔️ 
- Professional Readme file ✔️ 
- Descriptive commit messages ✔️ 
- Github flow used ✔️ 
- Descriptive Pull request ✔️ 

## Optional suggestions

- I would like to kindly suggest that you name your branch after a current feature you are to implement (e.g "setup-navbar", "add-form", "about-me-section" e.t.c) instead of using the name `feature` as your branch name 😉 🌸 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 08:12 UTC, merged